### ISSUE TITLE
Bridging Header and other API Issues

### ISSUE THREAD

**Issue by SabinKim** [amandachristy/Lion-Card-App#22]
Amanda and I are currently working on coding api request into swift. We still need some help on specifically writing the code. We read over the website that you gave us, but it is a little hard to understand. Also, we are still confused about how we will be able to connect our app with cardsmith. Are you still making our fake api request? Thank you.

**Comment by battis** [comment]
Hey guys — I'm way more likely to see this if you _assign_ it to me!

**Comment by battis** [comment]
So, [this tutorial](http://www.iteachcoding.com/how-to-hmac-sha1-sign-an-api-request-using-swift/) provides a bunch of helpful background (that you'll need to convert to reflect the CardSmith API). But they don't go into a lot of detail about how exactly the dang "bridging header" should be set up — [this tutorial is much more helpful](http://www.learnswiftonline.com/getting-started/adding-swift-bridging-header/) and reflects the changes that I made in [this commit](https://github.com/amandachristy/Lion-Card-App/commit/e17a3518b29a30586af235490e9d978a9fbcb43b).

**Comment by battis** [comment]
A further thought: I haven't looked into what the MozScape analytics API is returning as a response (that's the API in the tutorial), but the fact that there is a reference to columns in there makes me wonder if it returns a CSV-formatted response, rather than JSON. Something to be aware and thoughtful about as you adapt — you're receiving a JSON-formatted response from CardSmith, which should be easier to parse.

**Comment by battis** [comment]
Closing this out as "basically accomplished" — and you can refer to the [Swift example](https://github.com/battis/qdapi/tree/master/examples/swift) for accessing QDAPI as a model for accessing _any_ RESTful API.
